### ISSUE TITLE
orb appears to ignore config

### ISSUE THREAD

**Issue by kreezxil** [MattDahEpic/ExchangeOrb1.8#1]
while you may have fixed the texture, the orb doesn't appear to have a damage bar any longer. It feels as tho it is ignoring the server side config. nothing in console.

**Comment by MattDahEpic** [comment]
I am unable to reproduce the problem, but I have added a safeguard that I think will fix it. The damage bar problem may stem from the texture problem, as the texture now applies to all meta values but the damage bar might not. Try crafting a new orb and see if the problem persists.

I had removed the console logging a few versions ago and I have added it back in. The mod should tell you how many uses an orb has on startup and tell you how many uses are left on the orb when it is used in crafting.

**Comment by kreezxil** [comment]
I did notice the ":#" metavalue changing, just not the damage bar. Wouldn't
the same functions be involved as are used in tools, weapons and armors?
